# 1: sample names, 2: group (tumor/normal), 3: patient (common id)
samples: "samplesheets/niche1_samples_underscores.csv"

threads_set:
  threads_sys1: 7

cores: 30
snakemake: "--rerun-incomplete"

# set folder fastq files (without "/" at the end)
fastq_folder:
  ""

# set output folder results (without "/" at the end)
output_folder:
  "/shared/data/niche/Neoantigen_pipeline_runs/NICHE"

# set output folder DNA pipeline (without "/" at the end)
output_DNA_folder:
  "/shared/data/niche/Preprocessed_all_niche/"

# fill in correct read name (R1 and R2), characters after sample name before .fastq.gz
read_name:
  R1: "_R1_001"
  R2: "_R2_001"

params:
  bwa:
    ref: "/shared/data/niche/Reference_files/homo_sapiens/GRCh38_ensembl_105_primary_bwa/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz"
    threads: 10
  hlala:
    ref: "/shared/data/niche/Reference_files/homo_sapiens/GRCh38_1000gen/GRCh38_full_analysis_set_plus_decoy_hla.fa"
  pvactools:
    vaf_threshold: 0.05
  vep:
    cache_dir: "/shared/data/niche/Reference_files/homo_sapiens/GRCh38_VEP_direct"
    fasta: "/shared/data/niche/Reference_files/homo_sapiens/GRCh38_VEP_direct/homo_sapiens/105_GRCh38/Homo_sapiens.GRCh38.dna.toplevel.fa.gz"
    plugin_dir: "/shared/data/niche/Neoantigen_pipeline_v2/vep/plugins"
